services:
  fish_sizing-dev:
    container_name: ${PROJECT_NAME}-fish_sizing_u22
    build:
      context: .
      dockerfile: Dockerfile.fish_sizing_ubuntu_22
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: fish_sizing-dev

    runtime: nvidia            # <-- Add this line
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all       # <-- Add this if you want all GPUs
              capabilities: [gpu]
    environment:
      - DISPLAY=$CONTAINER_DISPLAY
    volumes:
      - ./:/home/rosuser/repo
      - ${DATASET}:/home/rosuser/dataset:rw
      - /media/slimbook/easystore/:/home/rosuser/easystore/:rw
      # - ${FISH_SIZING_PATH:-./external_repos/DL_utils}:/home/rosuser/repo/src/DL_utils/:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-/run/user/1000/gdm/Xauthority}:/home/rosuser/.Xauthority:rw
      - /dev:/dev
    networks:
      app-network:
        aliases:
          - fish-sizing_container
    tty: true
    stdin_open: true
    command: bash -c "tail -f /dev/null"
 
networks:
  app-network:
    name: ${PROJECT_NAME}-app-network
    driver: bridge
    attachable: true