# ==========================================
# CONFIGURACIÓN DEL PIPELINE DE PROCESAMIENTO
# ==========================================

# --- Parámetros de Imagen ---
decimation: 0.5           # Factor de escala (0.5 = mitad de resolución)
image_channels: 1         # 1 para escala de grises, 3 para color
pipeline_name: "basic"    # Nombre del pipeline definido en config.py

# --- Parámetros de Inferencia (YOLO) ---
model_path: "/home/slimbook/models/binary/yv11m/Pool_v5-revisada_no_duplicats_from_ckpt/40e_finetune_2/weights/last.pt"
conf_thr: 0.5             # Umbral de confianza para detección

# --- Parámetros de Estéreo y Medición ---
use_wls: True             # Aplicar filtro WLS a la disparidad
gt_ground_truth: 33.5
visualize: False          # Mostrar ventanas de OpenCV durante el proceso

# --- Otros ---
save_debug: False          # Guardar imágenes de diagnóstico (*_debug.jpg)

# --- Filtros de Calidad y Solapamiento ---
ignore_borders: False        # TRUE para medir aunque toque el borde
ignore_completeness: True   # TRUE para medir aunque la segmentación sea parcial
ignore_overlap: True        # TRUE para medir aunque haya solapamiento detectado
overlap_margin: 0.05        # Margen en metros para el chequeo de profundidad Z

ignore_aspect_ratio: True   # TRUE para medir aunque el pez esté de cara/curvado
aspect_ratio_thr: 2.0       # (Solo se aplica si ignore_aspect_ratio fuera false)