stereo:
  min_disparity: 0
  num_disparities: 128  # Multiplo de 16
  block_size: 5         # 3-7 suele ir bien
  p1_factor: 8
  p2_factor: 32
  disp12_max_diff: 1
  uniqueness_ratio: 10
  speckle_window_size: 100
  speckle_range: 32
  mode: "SGBM_3WAY"
  max_depth_meters: 4

wls:
  lambda: 8000.0   # Más alto = Más suavizado (probar 8000)
  sigma: 1.0       # Sensibilidad al color (1.0 - 2.0)